### ISSUE TITLE
good-loggly silently failing

### ISSUE THREAD

**Issue by dsernst** [fhemberger/good-loggly#10]
I have both `good-console` and `good-loggly` registered as reporters for:

```js
events: { log: '*', request: '*'},
```

I'm seeing the `good-console` logs appear like:

```
151012/172025.029, [response], http://0.0.0.0:8000: get /empire {} 200 (9ms) 
```

But nothing is showing up in loggly.

------------

From within `module.exports = internals.GoodLoggly = function (events, config) {`, I can add this line:

```
this._client.log({msg: 'hello worldfoobar'}, ['david-localhost'])
```

and that event will appear in loggly, including the tag. So it's not a credential problem or issue with the `loggly` package.

I can add a console log to `internals.GoodLoggly.prototype.init` which appears no problem.

But if I add a console log to `internals.GoodLoggly.prototype._report`, it never gets printed, even as I hit routes that appear in `good-console`. This suggests there's a problem with one of these lines: https://github.com/fhemberger/good-loggly/blob/master/lib/index.js#L45-L46

Should I investigate `squeeze`? It seems to be working for `good-console`.

**Comment by fhemberger** [comment]
Sorry to hear that. I haven't been using Loggly for over a year now, so unfortunately the development lags behind. If you can find an easy way to fix this, I'm more than happy for a PR.

I just noticed that good-console started to use squeeze differently, maybe it's just that …

**Comment by dsernst** [comment]
Interesting, thanks, I'll look into that.

Just curious— is there another logging provider you've been happier with?

On Tuesday, October 13, 2015, Frederic Hemberger <notifications@github.com>
wrote:

> Sorry to hear that. I haven't been using Loggly for over a year now, so
> unfortunately the development lags behind. If you can find an easy way to
> fix this, I'm more than happy for a PR.
>
> I just noticed that good-console started to use squeeze differently, maybe
> it's just that …
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fhemberger/good-loggly/issues/10#issuecomment-147625655>
> .
>


-- 
--
David Ernst

**Comment by dsernst** [comment]
Nevermind, turns out it was a problem with my configuration.

**Comment by fhemberger** [comment]
Ah, phew. ;)
