### ISSUE TITLE
Please update to good 6.0

### ISSUE THREAD

**Issue by mwawrusch** [fhemberger/good-loggly#2]
Hi, 
it would be awesome if you could update this module to support good 6.0. 

Thanks
Martin

**Comment by fhemberger** [comment]
Sure, but I need to investigate first what changes are required. Thanks for the heads up!

**Comment by fhemberger** [comment]
FYI: I started working on a branch to update good-loggly, still fighting a bit with the new streaming interface and the unit tests for it. But I think I can publish a version for you to test soon.

**Comment by mgartner** [comment]
@fhemberger any progress on this? Any way I can help out?

**Comment by fhemberger** [comment]
At the moment, it's mostly a severe lack of time on my side. And poorly documented code changes in Good. And getting the unit tests to work with the changes. (Oh, BTW: This reporter seems to be the only 3rd party reporter with tests/coverage at all, so there is no reference as well.)

I pushed everything I have come up with so far to this feature branch: https://github.com/fhemberger/good-loggly/tree/feature/good-6.0

It's mainly based on the changes of [good-console](https://github.com/hapijs/good-console/), a PR (especially regarding the unit tests) and testing in general would be highly appreciated.

**Comment by fhemberger** [comment]
@arb Thanks for offering to have a look at the issue. I'm not sure if I implemented the streaming interface correctly, I have also issues with the tests not working so far (I don't have much working experience with streams). Any help is highly appreciated.

**Comment by arb** [comment]
@fhemberger can you get on Gitter in https://gitter.im/hapijs/hapi and private message me some Loggly tokens I can use for testing?
